import { createHash } from 'node:crypto';
import { Decimal } from 'decimal.js';
import { featureMetadata } from './catalog.js';
import { evaluatePredicate } from './policy.js';
import { researchPacketSchema, type ResearchPacket } from './research.js';
import type { EvidenceRecord, FeatureResult, LiveCollection, LiveMarketSummary, Observation, Profile, QualityState, SemanticResult, Thesis, TokenRef } from './contracts.js';

export const baselineIds = ['O01','O02','O03','O04','O05','O06','O07','O08','O09','O10','O11','O12','O13','O14','O15','O16','O17','O18','O19','O20','O28','O30','A01','A02','A03','A04','A05','A06','A09','A10','A11','A14','A15','A16','A17','A18','A22','A23','S01','S02','S03','S04','S05','S06','S08','S10','C01','C02','C03','C04','C05','C06','C08','C09','C10','C11','C12','C13','C14','C15','C16'] as const;
export type MissingCause={category:'USER_INPUT_MISSING'|'EVIDENCE_UNAVAILABLE'|'COLLECTION_UNIMPLEMENTED'|'CLAIM_UNVALIDATED';code:string;featureId:string;sourceId?:string;field?:string;evidenceIds:string[];action:string};
export type BaselineAssessment={id:string;version:'baseline-v1';evaluator:'IMPLEMENTED';collector:'IMPLEMENTED'|'UNIMPLEMENTED'|'NOT_REQUIRED';quality:QualityState;unit:string;data:unknown;observationIds:string[];evidenceIds:string[];limitations:string[];causes:MissingCause[];projection?:FeatureResult};
export type ControlFacts={complete:boolean;supplyAllowed:boolean;transferAllowed:boolean;surfaceSupported:boolean;currentFeeBps:string|null;feeImmutable:boolean;controls:string[];unsupported:string[];evidenceIds:string[]};
export type HolderFacts={supplyAtomic:string;accounts:Array<{address:string;owner:string;amount:string}>;complete:boolean;evidenceIds:string[];slot:number};
export type ProgramFacts={address:string;loader:string;upgradeAuthority:string|null;immutable:boolean;authorityResolved?:boolean;programDataAddress?:string;deploymentSlot?:number;evidenceIds:string[]};
/** Internal direct adapter output. The research import schema cannot supply mechanical facts or certificates. */
export type VenueFacts={certificateId:string;bindingVerified:boolean;version:string;token:TokenRef;availableAt:string;expiresAt:string;removableLiquidityFraction:string;lockExpiresAt:string|null;entryQuoteUsd:string;acquiredAtomic:string;decimals:number;exitQuantityAtomic:string;exitQuoteUsd:string;referencePriceUsd:string;entryExternalCostUsd:string;exitExternalCostUsd:string;embeddedFeesUsd:string;costsReconciled:boolean;method:'INDEPENDENT_QUOTES'|'STATEFUL_QUOTED'|'SIMULATED';simulation?:{setupVerified:boolean;buySucceeded:boolean;sellSucceeded:boolean};evidenceIds:string[]};
export type VenueInspection={token:TokenRef;poolAddress:string;certificateId:string;version:string;availableAt:string;bindingVerified:boolean;evidenceIds:string[];removableLiquidityFraction?:string;executionDisabled?:boolean;errors:Record<string,string>;limitations:string[]};
export type BaselineInputs={sharedMode?:boolean;token:TokenRef;cutoff:string;profile:Profile;features:FeatureResult[];evidence:EvidenceRecord[];observations:Observation[];market?:LiveMarketSummary|null;collection?:LiveCollection;semantic?:SemanticResult;research?:ResearchPacket;attention?:BaselineAssessment[];social?:BaselineAssessment[];controls?:ControlFacts;holders?:HolderFacts;program?:ProgramFacts;venue?:VenueFacts;venueInspection?:VenueInspection;flow?:{buysUsd:string;sellsUsd:string;complete:boolean;start:string;end:string;evidenceIds:string[]};bots?:{coveredVolumeUsd:string;attributedVolumeUsd:string;verifiedIdentities:string[];evidenceIds:string[]};thesis?:Thesis;origins?:Record<string,string>;directErrors?:Record<string,string>};
const digest=(value:string)=>createHash('sha256').update(value).digest('hex');
const sameToken=(a:TokenRef,b:TokenRef)=>a.chain===b.chain&&(a.chain==='solana'?a.address===b.address:a.address.toLowerCase()===b.address.toLowerCase());
const namesAddress=(text:string,token:TokenRef)=>token.chain==='solana'?text.includes(token.address):text.toLowerCase().includes(token.address.toLowerCase());
const d=(v:Decimal.Value)=>new Decimal(v);
const within=(at:string,cutoff:string)=>Number.isFinite(Date.parse(at))&&Date.parse(at)<=Date.parse(cutoff);

export function validateResearch(input:unknown,token:TokenRef,cutoff:string):ResearchPacket {
  const packet=researchPacketSchema.parse(input);
  if (!sameToken(packet.token,token)) throw new Error('RESEARCH_TOKEN_MISMATCH');
  const records=new Map(packet.records.map(r=>[r.id,r]));
  if (records.size!==packet.records.length||new Set(packet.reviews.map(r=>r.recordId)).size!==packet.reviews.length) throw new Error('RESEARCH_DUPLICATE');
  const cite=(c:{recordId:string;quote:string})=>{const record=records.get(c.recordId);if(!record||!record.text.includes(c.quote))throw new Error('RESEARCH_CITATION');return record;};
  for(const record of packet.records) {
    if (!within(record.availableAt,cutoff)||!within(record.publishedAt,record.availableAt)||!record.tokenRefs.some(t=>sameToken(t,token))&&!packet.competitors?.candidates.some(c=>record.tokenRefs.some(t=>sameToken(t,c.token)))) throw new Error('RESEARCH_TIME_OR_BINDING');
    if(record.metrics&&(!within(record.publishedAt,record.metrics.observedAt)||!within(record.metrics.observedAt,cutoff))||record.accountCreatedAt&&!within(record.accountCreatedAt,record.publishedAt))throw new Error('RESEARCH_TIME_OR_BINDING');
    if(record.repostOf&&!records.has(record.repostOf))throw new Error('RESEARCH_LINEAGE');
  }
  for(const review of packet.reviews) {const record=cite(review);if(!within(review.reviewedAt,cutoff)||!within(record.availableAt,review.reviewedAt))throw new Error('RESEARCH_TIME_OR_BINDING');if(review.binding==='EXACT_CONTRACT'&&!record.tokenRefs.every(t=>namesAddress(record.text,t)))throw new Error('RESEARCH_CITATION');if(review.independentOriginProof)cite(review.independentOriginProof);}
  if(packet.narrative) {const n=packet.narrative;if(!within(n.reviewedAt,cutoff))throw new Error('RESEARCH_TIME_OR_BINDING');for(const c of [...n.citations,...(n.origin?[n.origin.citation]:[]),...(n.catalyst?[n.catalyst.citation]:[]),...(n.officialIdentity?[n.officialIdentity.citation,n.officialIdentity.primaryProof]:[]),...n.incentives.map(i=>i.citation)]) {const record=cite(c);if(!within(record.availableAt,n.reviewedAt))throw new Error('RESEARCH_TIME_OR_BINDING');}}
  if(packet.competitors)for(const candidate of packet.competitors.candidates){const identity=cite(candidate.identityEvidence);cite(candidate.association);if(!namesAddress(identity.text,candidate.token))throw new Error('RESEARCH_CITATION');}
  if(packet.corpus && (!within(packet.corpus.end,cutoff)||Date.parse(packet.corpus.start)>=Date.parse(packet.corpus.end)||((Date.parse(packet.corpus.end)-Date.parse(packet.corpus.start))/1000)%packet.corpus.bucketSeconds!==0||packet.records.length>packet.corpus.cap))throw new Error('RESEARCH_WINDOW');
  if(packet.context && (!within(packet.context.window.availableAt,cutoff)||!within(packet.context.window.end,packet.context.window.availableAt)||Date.parse(packet.context.window.start)>=Date.parse(packet.context.window.end)))throw new Error('RESEARCH_WINDOW');
  return packet;
}

export function deriveHolderBounds(input:HolderFacts) {
  if(!/^[1-9]\d*$/.test(input.supplyAtomic)||!Number.isSafeInteger(input.slot)||input.slot<0)throw new Error('HOLDER_SHAPE');
  const owners=new Map<string,bigint>(),seen=new Set<string>();let sum=0n;
  for(const a of input.accounts) {if(!a.owner||!a.address||seen.has(a.address)||!/^(0|[1-9]\d*)$/.test(a.amount))throw new Error('HOLDER_SHAPE');seen.add(a.address);const amount=BigInt(a.amount);sum+=amount;owners.set(a.owner,(owners.get(a.owner)??0n)+amount);}
  const supply=BigInt(input.supplyAtomic);if(sum>supply||input.complete&&sum!==supply)throw new Error('HOLDER_SUPPLY');
  const ranked=[...owners.entries()].filter(([,amount])=>amount>0n).sort((a,b)=>a[1]>b[1]?-1:a[1]<b[1]?1:a[0].localeCompare(b[0]));
  const fraction=(amount:bigint)=>d(amount.toString()).div(input.supplyAtomic).toFixed();
  const top=(n:number)=>ranked.slice(0,n).reduce((s,[,amount])=>s+amount,0n);
  return {sampleAccounts:input.accounts.length,ownerCountLowerBound:ranked.length,supplyAtomic:input.supplyAtomic,sampledAtomic:sum.toString(),sampledSupplyFraction:fraction(sum),unresolvedTailAtomic:(supply-sum).toString(),complete:input.complete,slot:input.slot,top1LowerBound:fraction(top(1)),top5LowerBound:fraction(top(5)),top10LowerBound:fraction(top(10)),largestProvenControlLowerBound:fraction(top(1)),top1UpperBound:fraction(top(1)+supply-sum),exclusions:[]};
}

export function deriveExecution(v:VenueFacts,token:TokenRef,profile:Profile,cutoff:string) {
  if(!v.certificateId||!v.bindingVerified||!sameToken(v.token,token)||!within(v.availableAt,cutoff)||Date.parse(v.expiresAt)<Date.parse(cutoff)||!profile.sizeUsd||!d(v.entryQuoteUsd).eq(profile.sizeUsd)||v.acquiredAtomic!==v.exitQuantityAtomic||!/^\d+$/.test(v.acquiredAtomic)||!d(v.acquiredAtomic).gt(0)||!Number.isInteger(v.decimals)||v.decimals<0||v.decimals>36)throw new Error('VENUE_SCOPE');
  for(const number of [v.entryQuoteUsd,v.exitQuoteUsd,v.referencePriceUsd,v.entryExternalCostUsd,v.exitExternalCostUsd,v.embeddedFeesUsd,v.removableLiquidityFraction])if(!d(number).isFinite()||d(number).lt(0))throw new Error('VENUE_NUMBER');
  if(d(v.referencePriceUsd).lte(0)||d(v.removableLiquidityFraction).gt(1))throw new Error('VENUE_NUMBER');
  const quantity=d(v.acquiredAtomic).div(d(10).pow(v.decimals)),reference=d(v.referencePriceUsd);
  const totalCost=d(v.entryQuoteUsd).add(v.entryExternalCostUsd),netExit=d(v.exitQuoteUsd).sub(v.exitExternalCostUsd);
  return {quantityTokens:quantity.toFixed(),entryImpactBps:Decimal.max(0,d(1).sub(quantity.div(d(v.entryQuoteUsd).div(reference))).mul(10000)).toFixed(),exitImpactBps:Decimal.max(0,d(1).sub(d(v.exitQuoteUsd).div(quantity.mul(reference))).mul(10000)).toFixed(),roundTripLossBps:Decimal.max(0,d(1).sub(netExit.div(totalCost)).mul(10000)).toFixed(),totalEntryCostUsd:totalCost.toFixed(),netExitUsd:netExit.toFixed(),embeddedFeesUsd:v.embeddedFeesUsd,method:v.method,costsReconciled:v.costsReconciled,removableLiquidityFraction:v.lockExpiresAt!==null&&Date.parse(v.lockExpiresAt)<Date.parse(cutoff)+(profile.horizonSeconds??0)*1000?'1':v.removableLiquidityFraction};
}

export function deriveCharts(series:NonNullable<ResearchPacket['candles']>,cutoff:string) {
  const bars=series.bars.filter(b=>within(b.end,cutoff)&&within(b.availableAt,cutoff));
  for(let i=0;i<bars.length;i++){const b=bars[i];if(Date.parse(b.end)-Date.parse(b.start)!==series.intervalSeconds*1000||!within(b.end,b.availableAt)||d(b.high).lt(Decimal.max(b.open,b.close,b.low))||d(b.low).gt(Decimal.min(b.open,b.close,b.high))||d(b.open).lte(0)||d(b.close).lte(0)||i>0&&Date.parse(b.start)!==Date.parse(bars[i-1].end))throw new Error('CANDLE_SHAPE_OR_GAP');}
  if(bars.length<2) return {returnFraction:null,drawdownFraction:null,trend:'UNKNOWN',pivots:[],tradeVwap:null};
  let peak=d(bars[0].close),drawdown=d(0);for(const b of bars){peak=Decimal.max(peak,b.close);drawdown=Decimal.max(drawdown,d(1).sub(d(b.close).div(peak)));}
  const pivots:Array<{kind:'HIGH'|'LOW';price:string;eventAt:string;confirmedAt:string;availableAt:string}>=[];
  for(let i=series.leftBars;i<bars.length-series.rightBars;i++){const window=bars.slice(i-series.leftBars,i+series.rightBars+1),bar=bars[i];const high=window.every(b=>b===bar||d(bar.high).gt(b.high)),low=window.every(b=>b===bar||d(bar.low).lt(b.low));if(high===low)continue;pivots.push({kind:high?'HIGH':'LOW',price:high?bar.high:bar.low,eventAt:bar.end,confirmedAt:bars[i+series.rightBars].end,availableAt:new Date(Math.max(...window.map(b=>Date.parse(b.availableAt)))).toISOString()});}
  const highs=pivots.filter(p=>p.kind==='HIGH').slice(-2),lows=pivots.filter(p=>p.kind==='LOW').slice(-2),compare=(values:typeof pivots)=>{const change=d(values[1].price).div(values[0].price).sub(1).mul(10000);return change.abs().lte(series.comparisonToleranceBps)?0:change.gt(0)?1:-1;};
  const trend=highs.length<2||lows.length<2?'UNKNOWN':compare(highs)===1&&compare(lows)===1?'UP':compare(highs)===-1&&compare(lows)===-1?'DOWN':compare(highs)===0&&compare(lows)===0?'RANGE':'MIXED';
  return {returnFraction:d(bars.at(-1)!.close).div(bars[0].open).sub(1).toFixed(),drawdownFraction:drawdown.toFixed(),trend,pivots,tradeVwap:null};
}

export function deriveMarketContext(context:NonNullable<ResearchPacket['context']>,token:TokenRef,cutoff:string) {
  const chains=['solana','bsc','base','robinhood'];if(new Set(context.chainVolumes.map(c=>c.chain)).size!==context.chainVolumes.length)throw new Error('CONTEXT_DUPLICATE');
  const covered=context.chainVolumes.filter(c=>c.complete),total=covered.reduce((sum,c)=>sum.add(c.usd),d(0)),previousTotal=covered.every(c=>c.previousUsd!==undefined)?covered.reduce((s,c)=>s.add(c.previousUsd!),d(0)):null;
  const activity={window:context.window,shareOfCoveredChains:covered.map(c=>({chain:c.chain,usd:c.usd,share:total.gt(0)?d(c.usd).div(total).toFixed():null,changePercentagePoints:previousTotal?.gt(0)&&total.gt(0)?d(c.usd).div(total).sub(d(c.previousUsd!).div(previousTotal)).mul(100).toFixed():null})),excludedChains:chains.filter(chain=>!covered.some(c=>c.chain===chain))};
  const ids=new Map<string,typeof context.bridges[number]>();let incoming=d(0),outgoing=d(0),pending=0;
  for(const bridge of context.bridges){const prior=ids.get(bridge.canonicalId);if(prior){if(JSON.stringify(prior)!==JSON.stringify(bridge))throw new Error('BRIDGE_CONFLICT');continue;}ids.set(bridge.canonicalId,bridge);if(!bridge.finalized||!bridge.completedAt||!within(bridge.completedAt,cutoff)){pending++;continue;}if(Date.parse(bridge.completedAt)<Date.parse(context.window.start)||Date.parse(bridge.completedAt)>=Date.parse(context.window.end))continue;if(bridge.to===token.chain)incoming=incoming.add(bridge.usd);if(bridge.from===token.chain)outgoing=outgoing.add(bridge.usd);}
  const bridge={inflowUsd:incoming.toFixed(),outflowUsd:outgoing.toFixed(),netUsd:incoming.sub(outgoing).toFixed(),pending,deduplicatedRecords:ids.size};
  if(new Set(context.macro.map(m=>m.instrument)).size!==context.macro.length)throw new Error('CONTEXT_DUPLICATE');
  const macro=context.macro.map(m=>({instrument:m.instrument,...deriveCharts({market:m.instrument,quote:m.quote,intervalSeconds:m.bars.length?Math.round((Date.parse(m.bars[0].end)-Date.parse(m.bars[0].start))/1000):1,leftBars:1,rightBars:1,comparisonToleranceBps:'0',bars:m.bars},cutoff)}));
  const launch=context.launch?{...context.launch,survivalFraction:context.launch.complete&&context.launch.cohortEnd&&context.launch.followupSeconds&&Date.parse(context.launch.cohortEnd)+context.launch.followupSeconds*1000<=Date.parse(cutoff)&&context.launch.survivors!==null&&context.launch.launches>0&&context.launch.survivors<=context.launch.launches?d(context.launch.survivors).div(context.launch.launches).toFixed():null}:null;
  return {activity,bridge,macro,launch,regime:{classification:null,meaning:'descriptive context; no fitted regime'}};
}

export function deriveBaseline(input:BaselineInputs):BaselineAssessment[] {
  const assessments=new Map<string,BaselineAssessment>();
  const cause=(id:string,category:MissingCause['category'],code:string,action:string,evidenceIds:string[]=[]):MissingCause=>({category,code,featureId:id,evidenceIds,action});
  const set=(id:string,data:unknown,options:{quality?:QualityState;unit?:string;ids?:string[];collector?:BaselineAssessment['collector'];limitations?:string[];causes?:MissingCause[];value?:string|boolean|null;projectionUnit?:string}={})=>{const quality=options.quality??'KNOWN',ids=options.ids??[];assessments.set(id,{id,version:'baseline-v1',evaluator:'IMPLEMENTED',collector:options.collector??'IMPLEMENTED',quality,unit:options.unit??'scoped-record',data,observationIds:[],evidenceIds:ids,limitations:options.limitations??[],causes:options.causes??[],...(options.value!==undefined?{projection:{id,value:options.value,unit:options.projectionUnit??(typeof options.value==='boolean'?'bool':options.unit??'count'),quality,availableAt:input.cutoff,evidenceIds:ids,applicability:'APPLICABLE'}}:{})});};
  for(const id of baselineIds) {const family=featureMetadata.find(f=>f.id===id)?.family;const claim=family==='ATTENTION'||family==='SOCIAL'||id==='C05';set(id,null,{quality:'MISSING',collector:claim?'IMPLEMENTED':'UNIMPLEMENTED',causes:[cause(id,claim?'CLAIM_UNVALIDATED':'COLLECTION_UNIMPLEMENTED',claim?'QUALIFIED_CORPUS_REQUIRED':'DIRECT_COLLECTOR_REQUIRED',claim?'Collect source-bound automated qualification for the named feature; extracted candidates alone cannot verify it.':'Implement and certify the named direct evidence adapter; do not substitute displayed market data.')]});}
  for(const f of input.features)if(assessments.has(f.id))set(f.id,{value:f.value,unit:f.unit},{quality:f.quality,unit:f.unit,ids:f.evidenceIds,value:f.value,projectionUnit:f.unit});
  if(input.collection){
    for(const id of ['O01','O02','O03','O04','O05','O06','O07','O17','O18','O19','O20']){
      const a=assessments.get(id)!;if(a.quality==='KNOWN')continue;
      const implemented=input.token.chain==='solana';
      a.collector=implemented?'IMPLEMENTED':'UNIMPLEMENTED';
      a.causes=[cause(id,implemented?'EVIDENCE_UNAVAILABLE':'COLLECTION_UNIMPLEMENTED',implemented?input.directErrors?.[['O17','O18','O19','O20'].includes(id)?'holders':id==='O05'?'program':'controls']??(id==='O02'?input.collection.dex.code:input.collection.rpc.code)??'DIRECT_STATE_UNAVAILABLE':'EVM_READER_UNIMPLEMENTED',implemented?'Run doctor --network and refresh finalized mint/program/owner evidence; a failed request is not absent implementation.':'Implement the chain-specific identity and control reader before accepting this feature.')];
    }
  }
  const completeProfile=!!input.profile.sizeUsd&&!!input.profile.horizonSeconds&&['maxTransferFeeBps','maxEntryImpactBps','maxExitImpactBps','maxRoundTripLossBps','maxDirectControlShare','maxRemovableLiquidityShare'].every(k=>input.profile.risk[k]!==undefined);
  set('C01',{profile:input.profile,quote:'USD',origins:input.origins??{},calibration:'UNCALIBRATED'},{ids:input.evidence.filter(e=>e.sourceId==='local-config').map(e=>e.id),collector:'NOT_REQUIRED',quality:completeProfile?'KNOWN':'MISSING',value:completeProfile,causes:completeProfile?[]:[cause('C01','USER_INPUT_MISSING','PROFILE_INCOMPLETE','Run config init to choose size, horizon and risk limits.')]});
  if(input.controls){const c=input.controls;for(const [id,value] of [['O03',c.supplyAllowed],['O04',c.transferAllowed],['O06',c.surfaceSupported]] as const)set(id,c,{ids:c.evidenceIds,quality:value===false||c.complete?'KNOWN':'UNSUPPORTED',value,limitations:c.unsupported,causes:!c.complete&&value!==false?[cause(id,'EVIDENCE_UNAVAILABLE','UNSUPPORTED_EXTENSION','Inspect the unresolved token extension before accepting control safety.',c.evidenceIds)]:[]});if(c.currentFeeBps!==null)set('O07',{currentBps:c.currentFeeBps,immutable:c.feeImmutable},{ids:c.evidenceIds,unit:'bps',value:c.currentFeeBps,quality:c.complete&&c.feeImmutable||input.profile.risk.maxTransferFeeBps!==undefined&&d(c.currentFeeBps).gt(input.profile.risk.maxTransferFeeBps)?'KNOWN':'MISSING',causes:c.complete&&c.feeImmutable||input.profile.risk.maxTransferFeeBps!==undefined&&d(c.currentFeeBps).gt(input.profile.risk.maxTransferFeeBps)?[]:[cause('O07','EVIDENCE_UNAVAILABLE','FEE_MUTABILITY','Resolve fee authority and future configuration through the holding horizon.',c.evidenceIds)]});}
  if(input.program)set('O05',input.program,{ids:input.program.evidenceIds,value:input.program.immutable,quality:input.program.immutable||input.program.authorityResolved?'KNOWN':'MISSING',limitations:input.program.authorityResolved&&!input.program.immutable?['Observed unrestricted upgrade authority; no policy allowlist or constraint proof is configured.']:[],causes:input.program.immutable||input.program.authorityResolved?[]:[cause('O05','EVIDENCE_UNAVAILABLE',input.directErrors?.program??'PROGRAM_UPGRADE_AUTHORITY','Review the observed program upgrade authority and its constraints.',input.program.evidenceIds)]});
  if(input.holders){const h=deriveHolderBounds(input.holders),quality=input.holders.complete?'KNOWN':'TRUNCATED';for(const id of ['O17','O18','O19','O20'])set(id,h,{ids:input.holders.evidenceIds,quality,unit:id==='O19'||id==='O20'?'fraction':'owner-sample',limitations:['Owners in a bounded account sample; no verified system-owner exclusions.'],causes:input.holders.complete?[]:[cause(id,'EVIDENCE_UNAVAILABLE','HOLDER_TAIL_UNKNOWN','Obtain a complete same-state owner distribution and proven control groups.',input.holders.evidenceIds)],...(id==='O19'?{value:h.top1LowerBound,projectionUnit:'fraction'}:id==='O20'?{value:h.largestProvenControlLowerBound,projectionUnit:'fraction'}:id==='O17'||id==='O18'?{value:true}:{})});}
  if(input.holders&&!input.holders.complete&&input.profile.risk.maxDirectControlShare!==undefined)for(const id of ['O19','O20']){
    const a=assessments.get(id)!;
    if(a.projection&&typeof a.projection.value==='string'&&d(a.projection.value).gt(input.profile.risk.maxDirectControlShare)){
      a.projection.quality='KNOWN';a.limitations.push('This lower bound alone exceeds the selected limit. It can reject concentration, never establish an acceptable complete distribution.');
    }
  }
  if(input.venueInspection){const v=input.venueInspection;
    if(!sameToken(v.token,input.token)||!within(v.availableAt,input.cutoff))throw new Error('VENUE_SCOPE');
    const bound=v.bindingVerified&&!!v.certificateId;
    set('O08',v,{ids:v.evidenceIds,value:bound,quality:bound?'KNOWN':'MISSING',limitations:v.limitations,causes:bound?[]:[cause('O08','EVIDENCE_UNAVAILABLE',v.errors.binding??'VENUE_BINDING_UNAVAILABLE','Refresh canonical PumpSwap pool/program/mint/vault state.',v.evidenceIds)]});
    if(bound&&v.removableLiquidityFraction!==undefined){if(!d(v.removableLiquidityFraction).isFinite()||d(v.removableLiquidityFraction).lt(0)||d(v.removableLiquidityFraction).gt(1))throw new Error('VENUE_NUMBER');set('O09',{fraction:v.removableLiquidityFraction,meaning:'all outstanding LP supply conservatively assumed withdrawable'},{ids:v.evidenceIds,unit:'fraction',value:v.removableLiquidityFraction,limitations:v.limitations});}
    for(const id of ['O09','O10','O11','O12','O13','O14','O15','O16'])if(assessments.get(id)?.quality!=='KNOWN')set(id,null,{collector:'IMPLEMENTED',quality:'MISSING',causes:[cause(id,'EVIDENCE_UNAVAILABLE',v.errors[id==='O09'?'liquidity':id==='O12'?'simulation':'execution']??(id==='O12'?v.errors.execution:undefined)??v.errors.binding??'VENUE_STATE_UNAVAILABLE','Refresh the supported PumpSwap operation and inspect its exact source/setup limitation.',v.evidenceIds)]});
    if(bound&&v.executionDisabled)for(const id of ['O10','O11'])set(id,{disabled:true},{ids:v.evidenceIds,value:false});
  }
  if(input.venue){const v=input.venue;
    const expired=Date.parse(v.expiresAt)<Date.parse(input.cutoff);
    if(expired){for(const id of ['O10','O11','O12','O13','O14','O15','O16'])set(id,null,{ids:v.evidenceIds,quality:'STALE',causes:[cause(id,'EVIDENCE_UNAVAILABLE','PUMP_QUOTE_EXPIRED','Refresh the supported route; quoted state expired before this analysis completed.',v.evidenceIds)]});}
    else {const x=deriveExecution(v,input.token,input.profile,input.cutoff);
      set('O08',{certificateId:v.certificateId,version:v.version,token:v.token},{ids:v.evidenceIds,value:true});
      set('O09',{fraction:x.removableLiquidityFraction,lockExpiresAt:v.lockExpiresAt},{ids:v.evidenceIds,unit:'fraction',value:x.removableLiquidityFraction});
      set('O10',{inputUsd:v.entryQuoteUsd,acquiredAtomic:v.acquiredAtomic},{ids:v.evidenceIds,value:true});
      set('O11',{quantityAtomic:v.exitQuantityAtomic,outputUsd:v.exitQuoteUsd,method:v.method},{ids:v.evidenceIds,value:true});
      for(const [id,value] of [['O13',x.entryImpactBps],['O14',x.exitImpactBps]] as const)set(id,x,{ids:v.evidenceIds,unit:'bps',value});
      for(const id of ['O15','O16'])set(id,x,{ids:v.evidenceIds,unit:id==='O15'?'bps':'bool',value:id==='O15'?x.roundTripLossBps:x.costsReconciled,quality:x.costsReconciled?'KNOWN':'MISSING',causes:x.costsReconciled?[]:[cause(id,'EVIDENCE_UNAVAILABLE',input.venueInspection?.errors.execution??'PUMP_TRANSACTION_COSTS_UNAVAILABLE','Collect transaction fees and account setup rent before evaluating total trade friction.',v.evidenceIds)]});
      if(v.simulation)set('O12',v.simulation,{ids:v.evidenceIds,value:v.simulation.setupVerified&&v.simulation.buySucceeded&&v.simulation.sellSucceeded,quality:v.simulation.setupVerified?'KNOWN':'MISSING'});
    }
  }
  const pair=input.market?.pairs.find(p=>p.mintSide==='base'&&p.priceUsd!==null&&p.buys24h!==null&&p.sells24h!==null&&p.volume24hUsd!==null);
  if(input.flow)set('O28',{...input.flow,netQuoteFlowUsd:d(input.flow.buysUsd).sub(input.flow.sellsUsd).toFixed()},{ids:input.flow.evidenceIds,unit:'USD/window',value:true,quality:input.flow.complete?'KNOWN':'TRUNCATED'});
  else if(pair)set('O28',{pair:pair.pairAddress,buys:pair.buys24h,sells:pair.sells24h,volumeUsd:pair.volume24hUsd,window:'rolling 24h',meaning:'trade counts; no buyer identity or organic-flow claim'},{ids:input.evidence.filter(e=>(input.sharedMode?e.id==='dex-pairs'&&(e.sourceId==='dexscreener'||e.sourceId==='tinyfish-fetch'&&e.scope.method==='tinyfish-live-dex-json-v1'):e.sourceId==='dexscreener')).map(e=>e.id),value:true});
  else set('O28',null,{quality:'MISSING',collector:'IMPLEMENTED',causes:[cause('O28','EVIDENCE_UNAVAILABLE','ACTIVITY_FIELDS_MISSING','Refresh exact-mint market data with price, counts and the reported rolling window.')]});
  if(input.bots){const b=input.bots;if(d(b.coveredVolumeUsd).lte(0)||d(b.attributedVolumeUsd).gt(b.coveredVolumeUsd)||!b.verifiedIdentities.length)throw new Error('BOT_ATTRIBUTION');set('O30',{...b,attributedFraction:d(b.attributedVolumeUsd).div(b.coveredVolumeUsd).toFixed()},{ids:b.evidenceIds,unit:'fraction'});}
  if(input.research)deriveCorpus(input,validateResearch(input.research,input.token,input.cutoff),set,cause);
  if(input.attention&&!input.research)for(const a of input.attention)assessments.set(a.id,a);
  if(input.social&&!input.research)for(const a of input.social)assessments.set(a.id,a);
  const requiredIds=new Set(['O01','O02','O03','O04','O05','O06','O07','O08','O09','O10','O11','O13','O14','O15','O16','O17','O18','O19','O20','O28','A01','A02','A03','A04','A05','A09','A10','A11','A14','A15','A16','A17','A18','S01','S02','S03','S04','S05','S06','S10']);
  const attentionAlternative=['A18','S10'].some(id=>{const a=assessments.get(id);return a?.projection?.quality==='KNOWN'&&a.projection.value===true;});
  const base=[...assessments.values()].filter(a=>requiredIds.has(a.id)&&!(attentionAlternative&&['A18','S10'].includes(a.id)&&a.quality!=='KNOWN'));let unresolved=base.filter(a=>a.quality!=='KNOWN');
  set('C02',{chain:input.token.chain,recognized:true,operations:{identity:input.features.some(f=>f.id==='O01'&&f.quality==='KNOWN'),market:!!input.market?.pairs.length,quote:!!input.venue,simulation:!!input.venue?.simulation,holders:!!input.holders,semantic:input.semantic?.status??'NOT_REQUESTED'},uncertifiedVenues:input.venue?[]:input.market?.pairs.map(p=>p.dexId)??[]},{ids:input.sharedMode?input.venueInspection?.evidenceIds??[]:[],quality:input.venue?'KNOWN':'MISSING',value:!!input.venue,causes:input.venue?[]:[cause('C02',input.venueInspection?'EVIDENCE_UNAVAILABLE':'COLLECTION_UNIMPLEMENTED',input.venueInspection?.errors.binding??input.venueInspection?.errors.execution??'VENUE_CERTIFICATION_MISSING',input.venueInspection?'Refresh the supported direct route; inspect its binding or execution error.':'Complete the chain/venue certificate and direct route adapter before claiming full entry coverage.',input.venueInspection?.evidenceIds??[])]});
  const freshness=base.map(a=>{
    const ttlSeconds=['O10','O11','O13','O14','O15','O16'].includes(a.id)?30:/^[AS]/.test(a.id)?900:300;
    const refs=a.evidenceIds.map(id=>input.evidence.find(e=>e.id===id));
    const eventAt=/^[AS]/.test(a.id)?input.research?.corpus?.end:input.features.find(f=>f.id===a.id)?.availableAt;
    const quoteAt=['O10','O11','O13','O14','O15','O16'].includes(a.id)?input.venue?.availableAt:undefined;
    const ages=[...refs.map(e=>e?Date.parse(input.cutoff)-Date.parse(e.retrievedAt):Infinity),...(eventAt?[Date.parse(input.cutoff)-Date.parse(eventAt)]:[]),...(quoteAt?[Date.parse(input.cutoff)-Date.parse(quoteAt)]:[])];
    return {id:a.id,ttlSeconds,eventAt:eventAt??quoteAt??null,evidenceIds:a.evidenceIds,fresh:refs.length>0&&refs.every(e=>!!e&&within(e.availableAt,input.cutoff))&&ages.every(age=>Number.isFinite(age)&&age>=0&&age<=ttlSeconds*1000)};
  });
  const fresh=freshness.length>0&&freshness.every(f=>f.fresh);
  for(const f of input.sharedMode?[]:freshness){const a=assessments.get(f.id)!;if(a.projection?.quality==='KNOWN'&&!f.fresh&&a.evidenceIds.length&&a.evidenceIds.every(id=>input.evidence.some(e=>e.id===id))){a.projection.quality='STALE';a.causes.push(cause(a.id,'EVIDENCE_UNAVAILABLE','FEATURE_TTL_EXCEEDED','Collect fresh evidence for this feature; a new retrieval cannot refresh an old completed event window.',a.evidenceIds));}}
  unresolved=base.filter(a=>a.quality!=='KNOWN'||a.projection?.quality==='STALE');
  set('C03',{method:'feature-ttl-v1',stateTtlSeconds:300,quoteTtlSeconds:30,socialTtlSeconds:900,records:freshness,requiredMissing:unresolved.map(a=>a.id)},{quality:fresh&&!unresolved.length?'KNOWN':'MISSING',value:fresh&&!unresolved.length,causes:fresh&&!unresolved.length?[]:[cause('C03','EVIDENCE_UNAVAILABLE',fresh?'REQUIRED_DEPENDENCY_MISSING':'EVIDENCE_STALE_OR_EMPTY','Refresh stale sources and complete missing required dependencies.')]});
  set('C04',{known:base.filter(a=>a.quality==='KNOWN').length,total:base.length,missing:unresolved.map(a=>a.id),collection:input.collection??null},{quality:unresolved.length?'MISSING':'KNOWN',value:!unresolved.length,causes:unresolved.length?[cause('C04','EVIDENCE_UNAVAILABLE','BASELINE_INCOMPLETE','Inspect the unresolved feature list; collection and qualification are separate tasks.')]:[]});
  const conflicts:Array<{field:string;ids:string[]}>=[];const fields=new Map<string,Observation[]>();for(const o of input.observations.filter(o=>o.quality==='KNOWN')){const key=`${o.field}:${o.observedAt}`;fields.set(key,[...(fields.get(key)??[]),o]);}for(const [field,os] of fields)if(new Set(os.map(o=>JSON.stringify(o.value))).size>1)conflicts.push({field,ids:os.map(o=>o.id)});
  set('C06',{conflicts,scope:'same field and observed instant',uninspected:unresolved.map(a=>a.id)},{quality:conflicts.length?'CONFLICT':unresolved.length?'MISSING':'KNOWN',value:!conflicts.length&&!unresolved.length,causes:conflicts.length||unresolved.length?[cause('C06','EVIDENCE_UNAVAILABLE',conflicts.length?'UNRESOLVED_CONFLICT':'CONFLICT_SCOPE_INCOMPLETE','Resolve comparable conflicting observations and complete the missing source scopes.')]:[]});
  if(input.thesis){const features=[...assessments.values()].flatMap(a=>a.projection?[a.projection]:[]);set('C10',{support:input.thesis.support.map(p=>({predicate:p,truth:evaluatePredicate(p,features,input.cutoff)})),invalidation:input.thesis.invalidation.map(p=>({predicate:p,truth:evaluatePredicate(p,features,input.cutoff)})),expiryAt:input.thesis.expiryAt,expired:!!input.thesis.expiryAt&&Date.parse(input.cutoff)>=Date.parse(input.thesis.expiryAt),catalyst:input.thesis.catalyst?{predicate:input.thesis.catalyst,truth:evaluatePredicate(input.thesis.catalyst,features,input.cutoff)}:null,onchainTraction:input.thesis.onchainTraction?{predicate:input.thesis.onchainTraction,truth:evaluatePredicate(input.thesis.onchainTraction,features,input.cutoff)}:null,externalTraction:input.thesis.externalTraction?{predicate:input.thesis.externalTraction,truth:evaluatePredicate(input.thesis.externalTraction,features,input.cutoff)}:null,warning:input.thesis.warning?{predicate:input.thesis.warning,truth:evaluatePredicate(input.thesis.warning,features,input.cutoff)}:null,legs:input.thesis.legs.map(leg=>({...leg,truth:evaluatePredicate(leg.trigger,features,input.cutoff)})),planReadiness:input.thesis.legs.length&&input.thesis.onchainTraction&&input.thesis.externalTraction?'SPECIFIED':'INCOMPLETE'},{collector:'NOT_REQUIRED'});}
  return baselineIds.map(id=>assessments.get(id)!);
}

type Setter=(id:string,data:unknown,options?:{quality?:QualityState;unit?:string;ids?:string[];collector?:BaselineAssessment['collector'];limitations?:string[];causes?:MissingCause[];value?:string|boolean|null;projectionUnit?:string})=>void;
type Cause=(id:string,category:MissingCause['category'],code:string,action:string,evidenceIds?:string[])=>MissingCause;
function deriveCorpus(input:BaselineInputs,packet:ResearchPacket,set:Setter,cause:Cause) {
  const ids=input.evidence.filter(e=>e.sourceId==='curated-research').map(e=>e.id),manifest=packet.corpus;
  const reviewed=new Map(packet.reviews.filter(r=>r.entailment==='DIRECT'&&r.binding!=='UNRESOLVED').map(r=>[r.recordId,r]));
  const inWindow=packet.records.filter(r=>!manifest||Date.parse(r.publishedAt)>=Date.parse(manifest.start)&&Date.parse(r.publishedAt)<Date.parse(manifest.end));
  const seen=new Set<string>(),originals=inWindow.filter(r=>{const normalized=r.text.normalize('NFKC').toLowerCase().replace(/\s+/g,' ').trim();const key=r.repostOf??digest(normalized);if(r.repostOf||seen.has(key))return false;seen.add(key);return true;});
  const allQualified=originals.filter(r=>{const label=reviewed.get(r.id);return label&&['CALL','NEWS','JOKE'].includes(label.role);});
  const qualified=allQualified.filter(r=>r.tokenRefs.some(t=>sameToken(t,input.token)));
  const authors=new Set(qualified.filter(r=>r.authorId!==null).map(r=>`${r.platform}:${r.authorId}`));
  const proven=qualified.filter(r=>reviewed.get(r.id)?.independentOriginProof&&r.originId),groups=new Set(proven.map(r=>r.originId)),communities=new Set(proven.filter(r=>r.communityId).map(r=>`${r.originId}:${r.communityId}`));
  const complete=!!manifest?.complete,allReviewed=originals.every(r=>reviewed.has(r.id));
  const quality:QualityState=complete?'KNOWN':'TRUNCATED';const uncertain=(id:string)=>[cause(id,'EVIDENCE_UNAVAILABLE','CORPUS_INCOMPLETE','Import a bounded corpus with an explicit complete query/window manifest.',ids)];
  set('A15',{raw:inWindow.length,originals:originals.length,cap:manifest?.cap??200,scope:manifest??null},{ids,quality,unit:'count',value:true,causes:complete?[]:uncertain('A15')});
  set('A16',{qualified:qualified.length,excluded:originals.filter(r=>reviewed.has(r.id)&&!qualified.includes(r)).map(r=>({id:r.id,role:reviewed.get(r.id)!.role})),unclassified:originals.filter(r=>!reviewed.has(r.id)).length},{ids,quality:complete&&allReviewed?'KNOWN':'MISSING',unit:'count',value:String(qualified.length),causes:allReviewed?complete?[]:uncertain('A16'):[cause('A16','CLAIM_UNVALIDATED','POST_LABELS_UNREVIEWED','Adjudicate the remaining exact-source post roles and binding.',ids)]});
  set('A17',{uniqueSourceAuthors:authors.size,unknownAuthors:qualified.filter(r=>r.authorId===null).length},{ids,quality:complete&&qualified.every(r=>r.authorId!==null)?'KNOWN':'MISSING',unit:'count',value:String(authors.size)});
  set('S02',{raw:inWindow.length,originals:originals.length,copies:inWindow.length-originals.length,method:'exact-repost-and-normalized-text-v1'},{ids,quality,value:true});
  set('S03',{provenOriginGroups:[...groups],unresolvedLineage:qualified.length-proven.length},{ids,quality:complete&&proven.length===qualified.length&&qualified.length>0?'KNOWN':'MISSING',value:groups.size>=2&&authors.size>=3});
  set('S10',{participatingCommunities:[...communities],scope:'explicit reviewed origins; not unique humans'},{ids,quality:complete&&proven.length===qualified.length&&qualified.length>0?'KNOWN':'MISSING',value:communities.size>=3});
  const maxBin=new Map<number,number>();for(const r of qualified){const bin=Math.floor(Date.parse(r.publishedAt)/60000);maxBin.set(bin,(maxBin.get(bin)??0)+1);}const sync=qualified.length?d(Math.max(0,...maxBin.values())).div(qualified.length).toFixed():null;
  set('S04',{oneMinutePeakFraction:sync,baseline:manifest?.coordinationBaselineFraction??null},{ids,quality:complete&&sync!==null&&manifest?.coordinationBaselineFraction!==undefined?'KNOWN':'MISSING',value:sync!==null&&manifest?.coordinationBaselineFraction!==undefined?d(sync).lte(manifest.coordinationBaselineFraction):null});
  const accountIndicators=qualified.map(r=>({id:r.id,accountAgeSeconds:r.accountCreatedAt?(Date.parse(r.publishedAt)-Date.parse(r.accountCreatedAt))/1000:null,activityIntervals:r.activityIntervalsSeconds??null}));
  set('S05',{accountIndicators,meaning:'observable indicators; no bot identity classifier'},{ids,quality:accountIndicators.length&&accountIndicators.every(a=>a.accountAgeSeconds!==null&&a.activityIntervals!==null)?'KNOWN':'MISSING',value:accountIndicators.length>0&&accountIndicators.every(a=>a.accountAgeSeconds!==null&&a.activityIntervals!==null)});
  const metricValues=qualified.filter(r=>r.metrics&&within(r.metrics.observedAt,input.cutoff));
  const requiredFields=['likes','replies','reposts'] as const;
  const metricCoverage=Object.fromEntries(requiredFields.map(field=>{const captured=metricValues.filter(r=>r.metrics![field]!==undefined).length;return [field,{captured,missing:qualified.length-captured}];}));
  const fullyCaptured=metricValues.filter(r=>requiredFields.every(field=>r.metrics![field]!==undefined));
  const engagementComplete=qualified.length>0&&fullyCaptured.length===qualified.length;
  const median=(xs:string[])=>{const sorted=xs.map(d).sort((a,b)=>a.cmp(b));return sorted.length?sorted[Math.floor(sorted.length/2)].toFixed():null;};
  set('S06',{captured:fullyCaptured.length,total:qualified.length,requiredFields,coverage:metricCoverage,medianLikes:median(metricValues.flatMap(r=>r.metrics?.likes!==undefined?[r.metrics.likes]:[])),medianReplies:median(metricValues.flatMap(r=>r.metrics?.replies!==undefined?[r.metrics.replies]:[])),medianReposts:median(metricValues.flatMap(r=>r.metrics?.reposts!==undefined?[r.metrics.reposts]:[])),meaning:'coverage of observed likes, replies and reposts; counts do not authenticate engagement'},{ids,quality:engagementComplete?'KNOWN':'MISSING',value:engagementComplete,causes:engagementComplete?[]:[cause('S06','EVIDENCE_UNAVAILABLE','ENGAGEMENT_FIELDS_MISSING','Supply observed likes, replies and reposts for every qualified original; explicit zero is an observation, omission is unknown.',ids)]});
  if(manifest){const duration=manifest.bucketSeconds*1000,end=Date.parse(manifest.end),previous=qualified.filter(r=>Date.parse(r.publishedAt)>=end-2*duration&&Date.parse(r.publishedAt)<end-duration).length,current=qualified.filter(r=>Date.parse(r.publishedAt)>=end-duration).length;set('A18',{previous,current,bucketSeconds:manifest.bucketSeconds,velocityPostsPerSecond:d(current).sub(previous).div(manifest.bucketSeconds).toFixed()},{ids,quality:complete&&allReviewed&&Date.parse(manifest.start)<=end-2*duration?'KNOWN':'MISSING',value:current>previous});}
  const labels=originals.flatMap(r=>reviewed.has(r.id)?[reviewed.get(r.id)!]:[]),paid=labels.filter(l=>l.paidDisclosure===true).length;
  set('A22',{disclosedPaidPosts:paid,undisclosed:labels.filter(l=>l.paidDisclosure===undefined).length,dexPaidOrders:null},{ids,quality:allReviewed?'KNOWN':'MISSING'});
  set('A23',{priceOnlyFraction:labels.length?d(labels.filter(l=>l.role==='PRICE_ONLY').length).div(labels.length).toFixed():null,unclassified:originals.length-labels.length},{ids,quality:labels.length&&allReviewed?'KNOWN':'MISSING',unit:'fraction'});
  const narrative=packet.narrative;
  if(narrative){const n=narrative,recordIds=n.citations.map(c=>c.recordId);const bound=recordIds.every(id=>reviewed.has(id)&&packet.records.find(r=>r.id===id)?.tokenRefs.some(t=>sameToken(t,input.token)));const q:QualityState=bound?'KNOWN':'MISSING';for(const [id,data,value] of [['A01',{description:n.description,narrativeId:digest(JSON.stringify(n.citations)+n.description)},true],['A02',{game:n.game},n.game!=='UNKNOWN'],['A05',{referent:n.referent,interest:n.interest,tokenRelation:n.tokenRelation,prerequisites:n.prerequisites},n.prerequisites.length===0],['A06',{style:n.style,meaning:'reviewed persistence hypothesis; no prediction'},n.style!=='UNKNOWN']] as const)set(id,data,{ids,quality:q,value});
    if(n.origin)set('A03',{...n.origin,meaning:'earliest observed reviewed source; not guaranteed true origin'},{ids,quality:bound&&n.origin.primary?'KNOWN':'MISSING',value:bound&&n.origin.primary});
    if(n.catalyst)set('A04',n.catalyst,{ids,quality:bound&&n.catalyst.kind==='FACT'?'KNOWN':'MISSING',value:n.catalyst.kind==='FACT'});
    set('S01',{claim:n.officialIdentity??null,scope:'human-reviewed corpus; optional official identity claim'},{ids,quality:n.officialIdentity?'MISSING':bound?'KNOWN':'MISSING',value:!n.officialIdentity&&bound,causes:n.officialIdentity?[cause('S01','CLAIM_UNVALIDATED','IDENTITY_AUTHENTICITY_UNRESOLVED','Verify the primary account/contract binding independently; citation presence is not authenticity.',ids)]:[]});
    set('S08',{disclosures:n.incentives,meaning:'explicit disclosed relationships only'},{ids,quality:bound?'KNOWN':'MISSING'});
  }
  const competitors=packet.competitors;
  if(competitors){const tokens=competitors.candidates.map(c=>c.token);if(new Set(tokens.map(t=>`${t.chain}:${t.address}`)).size!==tokens.length)throw new Error('COMPETITOR_DUPLICATE');const counts=tokens.map(token=>({token,count:allQualified.reduce((sum,r)=>{const associated=r.tokenRefs.filter(t=>tokens.some(c=>sameToken(c,t)));return associated.some(t=>sameToken(t,token))?sum.add(d(1).div(associated.length)):sum;},d(0))}));const total=counts.reduce((s,c)=>s.add(c.count),d(0)),sorted=[...counts].sort((a,b)=>b.count.cmp(a.count)),target=counts.find(c=>sameToken(c.token,input.token)),leader=target&&sorted[0]?.count.eq(target.count),ties=target?counts.filter(c=>c.count.eq(target.count)).length:0;set('A09',{query:competitors.query,tokens},{ids,quality:competitors.complete?'KNOWN':'TRUNCATED',value:competitors.complete&&tokens.length>1});set('A10',{associationEvidence:competitors.candidates.map(c=>c.association)},{ids,quality:competitors.complete?'KNOWN':'MISSING',value:competitors.complete&&!!target});set('A11',{shares:counts.map(c=>({token:c.token,count:c.count.toFixed(),share:total.gt(0)?c.count.div(total).toFixed():null})),scope:'observed reviewed competitor set'},{ids,quality:complete&&allReviewed&&competitors.complete&&qualified.length>=10&&tokens.length>1?'KNOWN':'MISSING',value:!!leader});set('A14',{leader:target?.token??null,tied:ties>1,margin:target&&sorted.length>1?target.count.sub(sorted[1].count).toFixed():null},{ids,quality:complete&&allReviewed&&competitors.complete&&qualified.length>=10&&tokens.length>1?'KNOWN':'MISSING',value:!!leader&&ties===1});}
  set('C05',{mode:'HUMAN_ADJUDICATED',reviewedRecords:reviewed.size,unreviewed:packet.records.length-reviewed.size,automatedQualityEvaluated:false},{ids,quality:reviewed.size&&allReviewed?'KNOWN':'MISSING',value:reviewed.size>0&&allReviewed});
  if(packet.candles){const chart=deriveCharts(packet.candles,input.cutoff);set('C08',chart,{ids,quality:chart.returnFraction!==null?'KNOWN':'MISSING'});set('C13',chart,{ids,quality:chart.trend==='UNKNOWN'?'MISSING':'KNOWN'});set('C14',{condition:packet.candles.chartCondition??null,result:!packet.candles.chartCondition?'NOT_REQUESTED':chart.trend==='UNKNOWN'?'UNKNOWN':chart.trend===packet.candles.chartCondition?'CORROBORATES':'CONTRADICTS'},{ids,quality:!packet.candles.chartCondition||chart.trend!=='UNKNOWN'?'KNOWN':'MISSING'});}
  if(packet.context){
    const context=deriveMarketContext(packet.context,input.token,input.cutoff);
    set('C11',context.activity,{ids,quality:context.activity.shareOfCoveredChains.length?'KNOWN':'MISSING'});
    set('C12',context.bridge,{ids,quality:packet.context.bridgeComplete?'KNOWN':'MISSING',causes:packet.context.bridgeComplete?[]:[cause('C12','EVIDENCE_UNAVAILABLE','BRIDGE_COVERAGE_UNDECLARED','Supply a complete declared bridge/window manifest before interpreting zero records as zero flow.',ids)]});
    set('C15',context.macro,{ids,quality:context.macro.length?'KNOWN':'MISSING'});
    set('C16',context.launch,{ids,quality:context.launch?packet.context.launch?.complete?'KNOWN':'TRUNCATED':'MISSING'});
    set('C09',{...context.regime,coverage:{chains:context.activity.shareOfCoveredChains.length,bridge:packet.context.bridgeComplete,macro:context.macro.length,launch:!!context.launch}},{ids,quality:context.activity.shareOfCoveredChains.length&&packet.context.bridgeComplete&&context.macro.length&&context.launch?'KNOWN':'MISSING'});
  }
}
