import type { EntryCheckDefinition, ManagementCheckDefinition } from './contracts.js';

/** Static feature metadata from plans/backend-v1/03-feature-registry.md. */
const featureMetadataById = {
  O01: { name: 'token identity', family: 'ONCHAIN' },
  O02: { name: 'supply and valuation', family: 'ONCHAIN' },
  O03: { name: 'supply authority', family: 'ONCHAIN' },
  O04: { name: 'transfer restrictions', family: 'ONCHAIN' },
  O05: { name: 'upgrade/control reachability', family: 'ONCHAIN' },
  O06: { name: 'extension/custom logic surface', family: 'ONCHAIN' },
  O07: { name: 'fee/tax mutability', family: 'ONCHAIN' },
  O08: { name: 'venue and lifecycle provenance', family: 'ONCHAIN' },
  O09: { name: 'liquidity withdrawal exposure', family: 'ONCHAIN' },
  O10: { name: 'entry route', family: 'ONCHAIN' },
  O11: { name: 'acquired-quantity exit', family: 'ONCHAIN' },
  O12: { name: 'execution simulation', family: 'ONCHAIN' },
  O13: { name: 'entry impact', family: 'ONCHAIN' },
  O14: { name: 'exit impact', family: 'ONCHAIN' },
  O15: { name: 'round-trip loss curve', family: 'ONCHAIN' },
  O16: { name: 'full cost breakdown', family: 'ONCHAIN' },
  O17: { name: 'holder data coverage', family: 'ONCHAIN' },
  O18: { name: 'economic holder count', family: 'ONCHAIN' },
  O19: { name: 'visible concentration', family: 'ONCHAIN' },
  O20: { name: 'proven control concentration', family: 'ONCHAIN' },
  O21: { name: 'inferred control topology', family: 'ONCHAIN' },
  O22: { name: 'fresh-wallet exposure', family: 'ONCHAIN' },
  O23: { name: 'synchronized entry/exit', family: 'ONCHAIN' },
  O24: { name: 'tracked inventory change', family: 'ONCHAIN' },
  O25: { name: 'inventory overhang proxies', family: 'ONCHAIN' },
  O26: { name: 'circular/round-trip patterns', family: 'ONCHAIN' },
  O27: { name: 'related-party volume', family: 'ONCHAIN' },
  O28: { name: 'directional flow', family: 'ONCHAIN' },
  O29: { name: 'thin-liquidity price inflation', family: 'ONCHAIN' },
  O30: { name: 'known automated flow', family: 'ONCHAIN' },

  A01: { name: 'narrative identity', family: 'ATTENTION' },
  A02: { name: 'game taxonomy', family: 'ATTENTION' },
  A03: { name: 'origin provenance', family: 'ATTENTION' },
  A04: { name: 'catalyst dependency', family: 'ATTENTION' },
  A05: { name: 'semantic compressibility', family: 'ATTENTION' },
  A06: { name: 'persistence class', family: 'ATTENTION' },
  A07: { name: 'narrative generativity', family: 'ATTENTION' },
  A08: { name: 'community artifact production', family: 'ATTENTION' },
  A09: { name: 'competitor candidate set', family: 'ATTENTION' },
  A10: { name: 'token-narrative binding', family: 'ATTENTION' },
  A11: { name: 'observed attention share', family: 'ATTENTION' },
  A12: { name: 'executable-liquidity share', family: 'ATTENTION' },
  A13: { name: 'participation-growth share', family: 'ATTENTION' },
  A14: { name: 'representation leadership', family: 'ATTENTION' },
  A15: { name: 'raw mention sample', family: 'ATTENTION' },
  A16: { name: 'qualified mention sample', family: 'ATTENTION' },
  A17: { name: 'author breadth', family: 'ATTENTION' },
  A18: { name: 'attention velocity', family: 'ATTENTION' },
  A19: { name: 'attention acceleration', family: 'ATTENTION' },
  A20: { name: 'propagation breadth', family: 'ATTENTION' },
  A21: { name: 'external-attention fraction', family: 'ATTENTION' },
  A22: { name: 'paid visibility', family: 'ATTENTION' },
  A23: { name: 'price-reflexive fraction', family: 'ATTENTION' },
  A24: { name: 'observed saturation proxies', family: 'ATTENTION' },
  A25: { name: 'attention/price lead-lag', family: 'ATTENTION' },
  A26: { name: 'attention-to-buyer proxy', family: 'ATTENTION' },
  A27: { name: 'marginal attention efficiency', family: 'ATTENTION' },
  A28: { name: 'observed decay half-life', family: 'ATTENTION' },
  A29: { name: 'distribution absorption', family: 'ATTENTION' },
  A30: { name: 'demand persistence', family: 'ATTENTION' },

  S01: { name: 'social identity binding', family: 'SOCIAL' },
  S02: { name: 'duplication structure', family: 'SOCIAL' },
  S03: { name: 'independent source groups', family: 'SOCIAL' },
  S04: { name: 'coordinated-post pattern', family: 'SOCIAL' },
  S05: { name: 'bot-like account indicators', family: 'SOCIAL' },
  S06: { name: 'engagement integrity', family: 'SOCIAL' },
  S07: { name: 'call-event extraction', family: 'SOCIAL' },
  S08: { name: 'promotional incentives', family: 'SOCIAL' },
  S09: { name: 'caller concentration', family: 'SOCIAL' },
  S10: { name: 'participating communities', family: 'SOCIAL' },
  S11: { name: 'returning participants', family: 'SOCIAL' },
  S12: { name: 'independent creators', family: 'SOCIAL' },
  S13: { name: 'public wallet association', family: 'SOCIAL' },
  S14: { name: 'actor entry lead', family: 'SOCIAL' },
  S15: { name: 'actor performance decomposition', family: 'SOCIAL' },
  S16: { name: 'copyable outcome', family: 'SOCIAL' },
  S17: { name: 'actor/follower alignment', family: 'SOCIAL' },
  S18: { name: 'actor observability proxies', family: 'SOCIAL' },
  S19: { name: 'independent actor convergence', family: 'SOCIAL' },
  S20: { name: 'promotion sequence recurrence', family: 'SOCIAL' },

  C01: { name: 'analysis context', family: 'SHARED' },
  C02: { name: 'capability coverage', family: 'SHARED' },
  C03: { name: 'evidence freshness', family: 'SHARED' },
  C04: { name: 'completeness/coherence', family: 'SHARED' },
  C05: { name: 'semantic validation', family: 'SHARED' },
  C06: { name: 'conflict register', family: 'SHARED' },
  C07: { name: 'lifecycle hypothesis', family: 'SHARED' },
  C08: { name: 'market-state context', family: 'SHARED' },
  C09: { name: 'chain-market regime', family: 'SHARED' },
  C10: { name: 'thesis conditions', family: 'SHARED' },
  C11: { name: 'chain DEX activity share', family: 'SHARED' },
  C12: { name: 'observed bridge flow', family: 'SHARED' },
  C13: { name: 'confirmed chart structure', family: 'SHARED' },
  C14: { name: 'chart-thesis corroboration', family: 'SHARED' },
  C15: { name: 'macro reference context', family: 'SHARED' },
  C16: { name: 'launchpad activity context', family: 'SHARED' },
} as const;

export const featureMetadata = Object.entries(featureMetadataById).map(([id, metadata]) => ({ id, ...metadata }));

export const entryDefinitions: EntryCheckDefinition[] = [
  { checkId: 'ID-01', role: 'HARD_GATE', pillar: 'SHARED', required: true, featureIds: ['O01'] },
  { checkId: 'CTX-01', role: 'REQUIRED_EVIDENCE', pillar: 'SHARED', required: true, featureIds: ['C01'] },
  { checkId: 'CAP-01', role: 'REQUIRED_EVIDENCE', pillar: 'SHARED', required: true, featureIds: ['C02', 'O08'] },
  { checkId: 'SEC-01', role: 'HARD_GATE', pillar: 'ONCHAIN', required: true, featureIds: ['O03'] },
  { checkId: 'SEC-02', role: 'HARD_GATE', pillar: 'ONCHAIN', required: true, featureIds: ['O04', 'O06'] },
  { checkId: 'SEC-03', role: 'HARD_GATE', pillar: 'ONCHAIN', required: true, featureIds: ['O05'] },
  { checkId: 'SEC-04', role: 'HARD_GATE', pillar: 'ONCHAIN', required: true, featureIds: ['O07'] },
  { checkId: 'SEC-05', role: 'HARD_GATE', pillar: 'ONCHAIN', required: true, featureIds: ['O08'] },
  { checkId: 'LIQ-01', role: 'HARD_GATE', pillar: 'ONCHAIN', required: true, featureIds: ['O09'] },
  { checkId: 'EXE-01', role: 'HARD_GATE', pillar: 'ONCHAIN', required: true, featureIds: ['O10', 'O11'] },
  { checkId: 'EXE-02', role: 'HARD_GATE', pillar: 'ONCHAIN', required: true, featureIds: ['O13', 'O14', 'O15', 'O16'] },
  { checkId: 'EXE-03', role: 'ADVISORY', pillar: 'ONCHAIN', required: false, featureIds: ['O12'] },
  { checkId: 'OWN-01', role: 'REQUIRED_EVIDENCE', pillar: 'ONCHAIN', required: true, featureIds: ['O17', 'O18'] },
  { checkId: 'OWN-02', role: 'HARD_GATE', pillar: 'ONCHAIN', required: true, featureIds: ['O19', 'O20'] },
  { checkId: 'MKT-01', role: 'REQUIRED_EVIDENCE', pillar: 'ONCHAIN', required: true, featureIds: ['O02', 'O28'] },
  { checkId: 'NAR-01', role: 'REQUIRED_EVIDENCE', pillar: 'ATTENTION', required: true, featureIds: ['A01', 'A02'] },
  { checkId: 'NAR-02', role: 'OPPORTUNITY', pillar: 'ATTENTION', required: true, featureIds: ['A03', 'A04'] },
  { checkId: 'NAR-03', role: 'OPPORTUNITY', pillar: 'ATTENTION', required: true, featureIds: ['A05'] },
  { checkId: 'CAN-01', role: 'REQUIRED_EVIDENCE', pillar: 'ATTENTION', required: true, featureIds: ['A09', 'A10'] },
  { checkId: 'CAN-02', role: 'OPPORTUNITY', pillar: 'ATTENTION', required: true, featureIds: ['A11', 'A14'] },
  { checkId: 'ATT-01', role: 'REQUIRED_EVIDENCE', pillar: 'ATTENTION', required: true, featureIds: ['A15', 'A16', 'A17'] },
  { checkId: 'ATT-02', role: 'OPPORTUNITY', pillar: 'SHARED', required: true, featureIds: ['A18', 'S10'] },
  { checkId: 'SOC-01', role: 'REQUIRED_EVIDENCE', pillar: 'SOCIAL', required: true, featureIds: ['S01'] },
  { checkId: 'SOC-02', role: 'REQUIRED_EVIDENCE', pillar: 'SOCIAL', required: true, featureIds: ['S02', 'S03', 'S04', 'S05', 'S06'] },
  { checkId: 'SOC-03', role: 'OPPORTUNITY', pillar: 'SOCIAL', required: true, featureIds: ['S03', 'S10'] },
  { checkId: 'DAT-01', role: 'REQUIRED_EVIDENCE', pillar: 'SHARED', required: true, featureIds: ['C03', 'C04'] },
  { checkId: 'DAT-02', role: 'REQUIRED_EVIDENCE', pillar: 'SHARED', required: true, featureIds: ['C05'] },
  { checkId: 'DAT-03', role: 'REQUIRED_EVIDENCE', pillar: 'SHARED', required: true, featureIds: ['C06'] },
  { checkId: 'ADV-01', role: 'ADVISORY', pillar: 'ONCHAIN', required: false, featureIds: ['O21', 'O22', 'O23', 'O24', 'O25'] },
  { checkId: 'ADV-02', role: 'ADVISORY', pillar: 'ONCHAIN', required: false, featureIds: ['O26', 'O27', 'O28', 'O29', 'O30'] },
  { checkId: 'ADV-03', role: 'ADVISORY', pillar: 'ATTENTION', required: false, featureIds: ['A06', 'A07', 'A08', 'A12', 'A13', 'A19', 'A20', 'A21', 'A22', 'A23', 'A24', 'A25', 'A26', 'A27', 'A28', 'A29', 'A30'] },
  { checkId: 'ADV-04', role: 'ADVISORY', pillar: 'SOCIAL', required: false, featureIds: ['S07', 'S08', 'S09', 'S11', 'S12', 'S13', 'S14', 'S15', 'S16', 'S17', 'S18', 'S19', 'S20'] },
  { checkId: 'ADV-05', role: 'ADVISORY', pillar: 'SHARED', required: false, featureIds: ['C07', 'C08', 'C09', 'C10', 'C11', 'C12', 'C13', 'C14', 'C15', 'C16'] },
];

export const managementDefinitions: ManagementCheckDefinition[] = [
  { checkId: 'MG-01', managementRole: 'REQUIRED_EVIDENCE', requiredFor: 'THESIS' },
  { checkId: 'MG-02', managementRole: 'SAFETY', requiredFor: 'THESIS' },
  { checkId: 'MG-03', managementRole: 'SAFETY', requiredFor: 'THESIS' },
  { checkId: 'MG-04', managementRole: 'REQUIRED_EVIDENCE', requiredFor: 'THESIS' },
  { checkId: 'MG-05', managementRole: 'CONTEXT', requiredFor: 'CONTEXT' },
  { checkId: 'MG-06', managementRole: 'VALIDATION', requiredFor: 'THESIS' },
  { checkId: 'MG-07', managementRole: 'INVALIDATION', requiredFor: 'THESIS' },
  { checkId: 'MG-08', managementRole: 'VALIDATION', requiredFor: 'THESIS' },
  { checkId: 'MG-09', managementRole: 'TRACTION', requiredFor: 'QUANTIFIED_PROPOSAL' },
  { checkId: 'MG-10', managementRole: 'TRACTION', requiredFor: 'QUANTIFIED_PROPOSAL' },
  { checkId: 'MG-11', managementRole: 'WARNING', requiredFor: 'WARNING' },
  { checkId: 'MG-12', managementRole: 'REALIZATION', requiredFor: 'QUANTIFIED_PROPOSAL' },
  { checkId: 'MG-13', managementRole: 'REQUIRED_FOR_QUANTIFIED_PROPOSAL', requiredFor: 'QUANTIFIED_PROPOSAL' },
  { checkId: 'MG-14', managementRole: 'INVALIDATION', requiredFor: 'THESIS' },
  { checkId: 'MG-15', managementRole: 'REQUIRED_FOR_QUANTIFIED_PROPOSAL', requiredFor: 'QUANTIFIED_PROPOSAL' },
];
